# Generated by Django 2.1.5 on 2020-02-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_post_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bads',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='goods',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
