# Generated by Django 2.1.5 on 2020-02-05 03:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0006_auto_20200205_0151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostFavorites',
            new_name='PostFavorite',
        ),
        migrations.RenameModel(
            old_name='UserFavorites',
            new_name='UserFavorite',
        ),
    ]
