# Generated by Django 2.1.5 on 2020-02-06 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20200205_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=2000, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
