# Generated by Django 2.1.5 on 2020-02-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200130_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
